In [1]:
import numpy as np
import cv2
import matplotlib
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
import os

In [3]:
os.chdir('../')
%pwd

'c:\\Users\\USER\\Documents\\JupyterNB\\ineuron\\Python Advanced\\football_player_classification'

In [4]:
face_cascade = cv2.CascadeClassifier('./haarcascades/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('./haarcascades/haarcascade_eye.xml')

In [5]:
def get_cropped_image_if_2_eyes(image_path):
    img = cv2.imread(image_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x,y,w,h) in faces:
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = img[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray)
        if len(eyes) >= 2:
            return roi_color

In [35]:
x = get_cropped_image_if_2_eyes('testing_images\lionel-messi-celebrates-after-their-sides-third-goal-by-news-photo-1686170172.jpg')

In [36]:
print(x)

[[[ 71  76 101]
  [ 72  77 102]
  [ 74  79 104]
  ...
  [ 73  81 111]
  [ 75  80 111]
  [ 76  81 112]]

 [[ 69  74  99]
  [ 71  76 101]
  [ 74  79 104]
  ...
  [ 72  80 110]
  [ 74  79 110]
  [ 75  80 111]]

 [[ 68  73  98]
  [ 71  76 101]
  [ 74  79 104]
  ...
  [ 71  79 109]
  [ 71  79 109]
  [ 72  80 110]]

 ...

 [[206 205 207]
  [213 212 214]
  [216 215 217]
  ...
  [ 97  89 100]
  [ 99  91 102]
  [100  92 103]]

 [[206 205 207]
  [216 215 217]
  [215 214 216]
  ...
  [ 98  90 101]
  [100  92 103]
  [102  94 105]]

 [[206 205 207]
  [213 212 214]
  [211 210 212]
  ...
  [ 99  91 102]
  [101  93 104]
  [103  95 106]]]


In [6]:
path_to_data = "./dataset/"
path_to_cr_data = "./dataset/cropped/"

In [7]:
img_dirs = []
for entry in os.scandir(path_to_data):
    if entry.is_dir():
        img_dirs.append(entry.path)


In [8]:
img_dirs

['./dataset/Messi', './dataset/Neymar', './dataset/Ronaldo']

In [9]:
import shutil
if os.path.exists(path_to_cr_data):
     shutil.rmtree(path_to_cr_data)
os.mkdir(path_to_cr_data)

In [10]:
cropped_image_dirs = []
player_file_names_dict = {}

In [30]:
from PIL import Image

for img_dir in img_dirs:
    count = 1
    player_name = img_dir.split('/')[-1]
    print(player_name)
    
    player_file_names_dict[player_name] = []
    
    for entry in os.scandir(img_dir):
        print(entry.path)
       
        try:

            roi_color = get_cropped_image_if_2_eyes(entry.path)
            if roi_color is not None:
                cropped_folder = path_to_cr_data + player_name
                if not os.path.exists(cropped_folder):
                    os.makedirs(cropped_folder)
                    cropped_image_dirs.append(cropped_folder)
                    print("Generating cropped images in folder: ",cropped_folder)
                    
                cropped_file_name = player_name + str(count) + ".png"
                cropped_file_path = cropped_folder + "/" + cropped_file_name 
                
                cv2.imwrite(cropped_file_path, roi_color)
                print(count)
                player_file_names_dict[player_name].append(cropped_file_path)
                count += 1  
        except Exception as e:
            continue

Messi
./dataset/Messi\-1x-1.jpg
./dataset/Messi\00001-tls-pro-tls1.jpg
Generating cropped images in folder:  ./dataset/cropped/Messi
1
./dataset/Messi\00002-tls-pro-tls1.jpg
2
./dataset/Messi\000_32UQ9KZ.jpg
./dataset/Messi\009d07f5675b73b7e5ada151c73b131861d65305ec12a.jpg
./dataset/Messi\00d3d92a-d82c-487e-96c7-2570dce5aecf_alta-libre-aspect-ratio_default_0.jpg
3
./dataset/Messi\019a33165f89be9172407356e7767d1a.png
4
./dataset/Messi\01ggq164zha1gxkn61zq.jpg
5
./dataset/Messi\0246760e-c223-4425-925c-3118edf960be.webp
./dataset/Messi\068d037c-bf95-4391-9fbf-119abe9fd962.jpg
./dataset/Messi\0713_AppleMessi-scaled.jpg
6
./dataset/Messi\0721_Messi_TheMoney-scaled.jpg
./dataset/Messi\07261cd4-1c68-4906-abe3-26ac487b19cf.jpg
./dataset/Messi\084702d2-messi1.jpg
./dataset/Messi\0955533672f52ad5ccdd9a1bc862e7ea--lionel-messi-leo.jpg
7
./dataset/Messi\0b7e9cb5-6dfe-4621-b9f8-1cf098e808c6.jpg
8
./dataset/Messi\0bb0272e617fa7e1b5a630bd5328c3af.jpg
9
./dataset/Messi\0d070e3d-761a-5e0d-a1aa-90c10535